### PR TITLE
CSUB-536: re-added staking pools

### PR DESCRIPTION
**Pull request by zacharyfrederick**

### CODE REVIEW

**Review by atodorov — CHANGES_REQUESTED** [review]
I am having troubles joining a pool from a second account. 

1) Using ATODOROV NOMINATOR I create a pool and stake 100k with it. The pool becomes active and nominates both Alice and Bob as validators. 

2) Then as N02 I select to join the existing pool and select maximum stake ~ 300 CTC. Transaction is submitted and shortly after it is included in a block. The only thing I see in Polkadot JS apps is utility.BatchInterrupted error: 

image


If I select a smaller amount, e.g. 200 CTC then I get "Transaction was initiated: Pending" notification and nothing else afterwards. I can keep doing this over and over but can't join the existing pool.

**Comment by zacharyfrederick** [comment]
@atodorov 

Has an era passed and are you running with fast runtime?

**Comment by atodorov** [comment]
> @atodorov
> 
> Has an era passed 

Yes. 

> and are you running with fast runtime?

Yes


I recreated my scenario from scratch. Upon creating the pool I also see this: 
image

however the pool is created just fine.

**Comment by zacharyfrederick** [comment]
Let me double check all the commits that have to do with removing pools and
see if I forgot to wire anything back together. It should all be enabled on
the rust side right?

**Review by atodorov — APPROVED** [review]
With the patch from https://github.com/gluwa/creditcoin/pull/1379 I can create pools via Staking Dashboard, wait for an era to pass and the pool becomes inactive. Validators backed by the pool start displaying "Other stake". 

As another nominator account I can join the existing pool and after 1 era has elapsed I see that "Other stake" for validators has been updated to reflect the new amount of CTC in the pool.

**Pull request closed without merging**
